language: generic

branches:
  only:
    - master
cache:
  directories:
  - $HOME/.cabal
  - $HOME/.stack
addons:
  apt:
    packages:
      - libgmp-dev
before_install:
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install:
# Build dependencies
- stack --no-terminal --install-ghc test --only-dependencies
- if ! which hlint; then stack --no-terminal install hlint; fi

script:
# Build the package, its tests, and its docs and run the tests
- stack --no-terminal test --haddock --no-haddock-deps
- hlint .
