language: haskell
cache:
  directories:
    - $HOME/.stack
before_install:
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  - stack config set system-ghc --global true
  - export PATH=/opt/ghc/8.0.2/bin:$PATH
addons:
  apt:
    sources:
    - hvr-ghc
    packages:
    - ghc-8.0.2
    - stack --no-terminal --install-ghc test --only-dependencies
install:
#  - stack setup --no-terminal
#  - stack build --only-snapshot --no-terminal
script:
  - curl -sL https://raw.github.com/ndmitchell/hlint/master/misc/travis.sh | sh -s .
  - stack test
